# Generated by Django 3.2.5 on 2022-12-21 07:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('zephyr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
