# Generated by Django 3.2.5 on 2023-01-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zephyr', '0004_ca_permanent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
