# Generated by Django 3.2.5 on 2023-01-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zephyr', '0005_alter_ca_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ca',
            old_name='permanent_address',
            new_name='sop',
        ),
    ]
