# Generated by Django 3.2.5 on 2023-01-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zephyr', '0006_rename_permanent_address_ca_sop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='email',
            field=models.EmailField(max_length=254, unique='True'),
        ),
    ]
