# Generated by Django 3.2.5 on 2023-01-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zephyr', '0007_alter_ca_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ca',
            old_name='sop',
            new_name='statement_of_purpose',
        ),
    ]
